## Inicio da predição (Bases desbalanceadas e tweets neutros com coisa)

In [ ]:
import pandas as pd
#df_ofensa = pd.read_csv('tweets_ofensivos_finais_com_ofensa.csv')
#df_neutro = pd.read_csv('tweets_neutros_finais_com_coisa.csv')

In [ ]:
df_ofensa.head()

text
0  rt @mariama59879065 tvi ficava melhor prolonga...
1  = mang trong minh dong mau lac hong phai cu go...
2                                         tomamo cu 
3  n entendo oq passa cabeca dessas pessoas namor...
4                 vai tomar cu professor filho puta

In [ ]:
df_ofensa.insert(1, 'classe', 1)

In [ ]:
df_neutro.head()

text
0  nunca lido ansiedade medo d faze alguma coisa ...
1                                  fiz alguma coisa 
2   @seekzisgarb poa mt coisa pra fzr alem show tue 
3  pensei mesma coisa akkakakakakkkakakak confirm...
4                 coisa linda https t co/tdhc42gyyc

In [ ]:
df_neutro.insert(1, 'classe', 0)

In [ ]:
import numpy as np

from sklearn.naive_bayes import MultinomialNB

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split

In [ ]:
frames = [df_ofensa, df_neutro]
df_geral = pd.concat(frames)

In [ ]:
df_geral.head()

text  classe
0  rt @mariama59879065 tvi ficava melhor prolonga...       1
1  = mang trong minh dong mau lac hong phai cu go...       1
2                                         tomamo cu        1
3  n entendo oq passa cabeca dessas pessoas namor...       1
4                 vai tomar cu professor filho puta        1

In [ ]:
df_geral = df_geral.sample(frac=1).reset_index(drop=True)

In [ ]:
df_geral.head()

text  classe
0            sanguessuga hoje vai ser criar pra mim        1
1  @mister_wolf_0 @pamjiles vieja loca y mentiros...       1
2  rt @rn_jonathas @euclides_crf todos utilizados...       1
3  comprei monte coisa shoppe pra fazer surpresa ...       0
4  coco desgraca corretor sio https t co/rutjgjynqn        1

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(df_geral.text, df_geral.classe, test_size=0.3)

In [ ]:
vect = CountVectorizer(ngram_range=(2,2))
X_train = vect.fit_transform(x_train)
X_test = vect.transform(x_test)

In [ ]:
mnb = MultinomialNB(alpha =0.2)

mnb.fit(X_train,y_train)

result= mnb.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(result,y_test)

0.8925092374874034

In [ ]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, result)

array([[ 948,   88],
       [ 232, 1709]], dtype=int64)

In [ ]:
from sklearn.metrics import f1_score
f1_score(result, y_test)

0.9143927233814874

In [ ]:
df_geral['classe'].value_counts()

1    6608
0    3314
Name: classe, dtype: int64

## Criação do modelo com base "mais" balanceada e sem a palavra coisa.

In [ ]:
df_ofensa = pd.read_csv('tweets_ofensivos_finais_com_ofensa.csv')
df_neutro = pd.read_csv('tweets_neutros_finais_sem_coisa.csv')

In [ ]:
df_ofensa.head()

text
0  rt @mariama59879065 tvi ficava melhor prolonga...
1  = mang trong minh dong mau lac hong phai cu go...
2                                         tomamo cu 
3  n entendo oq passa cabeca dessas pessoas namor...
4                 vai tomar cu professor filho puta

In [ ]:
df_ofensa.insert(1, 'classe', 1)

In [ ]:
df_neutro.head()

text
0  fiquei sinal hoje dia todo chego casa surto la...
1  @haddad_fernando @clagraca honestidade ultima ...
2  bolsonaro poderia pior presidente toda histori...
3  q comecar ter consciencia amigos  ter relacao ...
4  assisti ta lista quero ver  https t co/h7uhvbq...

In [ ]:
df_neutro.insert(1, 'classe', 0)

In [ ]:
frames = [df_ofensa, df_neutro]
df_geral = pd.concat(frames)

In [ ]:
df_geral.head()

text  classe
0  rt @mariama59879065 tvi ficava melhor prolonga...       1
1  = mang trong minh dong mau lac hong phai cu go...       1
2                                         tomamo cu        1
3  n entendo oq passa cabeca dessas pessoas namor...       1
4                 vai tomar cu professor filho puta        1

In [ ]:
df_geral = df_geral.sample(frac=1).reset_index(drop=True)

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(df_geral.text, df_geral.classe, test_size=0.3)

In [ ]:
vect = CountVectorizer(ngram_range=(2,2))
X_train = vect.fit_transform(x_train)
X_test = vect.transform(x_test)

In [ ]:
mnb = MultinomialNB(alpha =0.2)

mnb.fit(X_train,y_train)

result= mnb.predict(X_test)

MultinomialNB(alpha=0.2)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(result,y_test)

NameError: name 'result' is not defined

In [ ]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, result)

array([[ 717,  572],
       [ 258, 1689]])

In [ ]:
from sklearn.metrics import f1_score
f1_score(result, y_test)

0.8027566539923954

In [ ]:
df_geral['classe'].value_counts()

1    6608
0    4178
Name: classe, dtype: int64

In [ ]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(mnb, vect.transform(df_geral['text']), df_geral['classe'], cv=5)

In [ ]:
scores.mean()

0.519655212268782

## Teste Retirando os tweets com ofensas da base neutra e balanceando as duas bases

In [1]:
import numpy as np

from sklearn.naive_bayes import MultinomialNB

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split

In [3]:
import pandas as pd
df_ofensa = pd.read_csv('tweets_ofensivos_finais_com_ofensa.csv')
df_neutro = pd.read_csv('tweets_neutros_finais_sem_coisa_nem_ofensa.csv')

In [4]:
df_neutro.insert(1, 'classe', 0)
df_ofensa.insert(1, 'classe', 1)

In [5]:
df_ofensa = df_ofensa.sample(frac=1).reset_index(drop=True)

In [6]:
df_ofensa.head()

text  classe
0  @edricblight_b0t ah chinga /se tapa la boca co...       1
1  la temporada 2 #lajauria2 es sordida ideologiz...       1
2  rt @odeputadobanido vergonhoso premio 1 6 milh...       1
3                        @hollowprlple boco zap zap        1
4  @drabinskiariel @_loac_lawyer @pawel_zariczny ...       1

In [7]:
df_neutro.count()

text      2836
classe    2836
dtype: int64

In [8]:
df_ofensa = df_ofensa.iloc[0:2836,:]

In [9]:
df_ofensa.count()

text      2836
classe    2836
dtype: int64

In [10]:
frames = [df_ofensa, df_neutro]
df_geral = pd.concat(frames)
df_geral = df_geral.sample(frac=1).reset_index(drop=True)

In [11]:
df_geral['classe'].value_counts()

1    2836
0    2836
Name: classe, dtype: int64

In [12]:
import numpy as np
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(df_geral.text, df_geral.classe, test_size=0.3)
vect = CountVectorizer(ngram_range=(2,2))
X_train = vect.fit_transform(x_train)
X_test = vect.transform(x_test)

In [13]:
mnb = MultinomialNB(alpha =0.2)

mnb.fit(X_train,y_train)

result= mnb.predict(X_test)

In [14]:
from sklearn.metrics import accuracy_score
accuracy_score(result,y_test)

0.663337250293772

In [15]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, result)

array([[788,  61],
       [512, 341]])

In [16]:
from sklearn.metrics import f1_score
f1_score(result, y_test)

0.543426294820717

In [17]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(mnb, vect.transform(df_geral['text']), df_geral['classe'], cv=5)
scores.mean()

0.6135415549806151